/**
 * @packageDocumentation
 * RuleTester coverage for `no-conflicting-config-link-props`.
 */
import { createRuleTester, getPluginRule } from "./_internal/ruleTester";

const ruleTester = createRuleTester();

ruleTester.run(
    "no-conflicting-config-link-props",
    getPluginRule("no-conflicting-config-link-props"),
    {
        invalid: [
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    label: "Docs",',
                    '                    to: "/docs/intro",',
                    '                    href: "/docs/intro",',
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "noConflictingConfigLinkProps" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                output: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    label: "Docs",',
                    '                    to: "/docs/intro",',
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
            },
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        footer: {",
                    "            links: [",
                    "                {",
                    '                    title: "Project",',
                    "                    items: [",
                    "                        {",
                    '                            label: "GitHub",',
                    '                            to: "https://github.com/Nick2bad4u/eslint-plugin-docusaurus-2",',
                    '                            href: "https://github.com/Nick2bad4u/eslint-plugin-docusaurus-2",',
                    "                        },",
                    "                    ],",
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "noConflictingConfigLinkProps" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                output: [
                    "export default {",
                    "    themeConfig: {",
                    "        footer: {",
                    "            links: [",
                    "                {",
                    '                    title: "Project",',
                    "                    items: [",
                    "                        {",
                    '                            label: "GitHub",',
                    '                            href: "https://github.com/Nick2bad4u/eslint-plugin-docusaurus-2",',
                    "                        },",
                    "                    ],",
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
            },
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    label: "Docs",',
                    '                    to: "/docs/intro",',
                    '                    href: "https://example.com/docs",',
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "noConflictingConfigLinkProps" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
        ],
        valid: [
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    label: "Docs",',
                    '                    to: "/docs/intro",',
                    "                },",
                    "                {",
                    '                    label: "GitHub",',
                    '                    href: "https://github.com/Nick2bad4u/eslint-plugin-docusaurus-2",',
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: 'export default { to: "/docs/intro", href: "/docs/intro" };',
                filename: "src/config.ts",
            },
        ],
    }
);
