/**
 * @packageDocumentation
 * RuleTester coverage for `no-duplicate-plugin-pwa-head-tags`.
 */
import { createRuleTester, getPluginRule } from "./_internal/ruleTester";

const ruleTester = createRuleTester();

ruleTester.run(
    "no-duplicate-plugin-pwa-head-tags",
    getPluginRule("no-duplicate-plugin-pwa-head-tags"),
    {
        invalid: [
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [",
                    '                    { tagName: "link", rel: "manifest", href: "/manifest.json" },',
                    '                    { tagName: "link", rel: "manifest", href: "/manifest.json" },',
                    "                ],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "noDuplicatePluginPwaHeadTags" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                output: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [",
                    '                    { tagName: "link", rel: "manifest", href: "/manifest.json" },',
                    "                ],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [",
                    '                    { tagName: "meta", name: "theme-color", content: "#25c2a0" },',
                    '                    { content: "#25c2a0", name: "theme-color", tagName: "meta" },',
                    "                ],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "noDuplicatePluginPwaHeadTags" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                output: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [",
                    '                    { tagName: "meta", name: "theme-color", content: "#25c2a0" },',
                    "                ],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
            },
            {
                code: [
                    "const pwaHead = [",
                    '    { tagName: "meta", name: "theme-color", content: "#25c2a0" },',
                    '    { tagName: "meta", name: "theme-color", content: "#25c2a0" },',
                    "];",
                    "",
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "noDuplicatePluginPwaHeadTags" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                output: [
                    "const pwaHead = [",
                    '    { tagName: "meta", name: "theme-color", content: "#25c2a0" },',
                    "];",
                    "",
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
            },
        ],
        valid: [
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [",
                    '                    { tagName: "link", rel: "manifest", href: "/manifest.json" },',
                    '                    { tagName: "meta", name: "theme-color", content: "#25c2a0" },',
                    "                ],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "const pwaHead = [",
                    '    { tagName: "meta", name: "theme-color", content: pwaThemeColor },',
                    "    ...extraTags,",
                    "];",
                    "",
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [",
                    '                    { tagName: "link", rel: "manifest", href: "/manifest.json" },',
                    '                    { tagName: "link", rel: "manifest", href: `/' +
                        "${" +
                        "manifestName}` },",
                    "                ],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [",
                    '                    { tagName: "link", rel: "manifest", href: "/manifest.json" },',
                    '                    { tagName: "link", rel: "manifest", href: "/manifest.json" },',
                    "                ],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "src/config.ts",
            },
        ],
    }
);
