/**
 * @packageDocumentation
 * RuleTester coverage for `require-plugin-pwa-debug`.
 */
import { createRuleTester, getPluginRule } from "./_internal/ruleTester";

const ruleTester = createRuleTester();

ruleTester.run(
    "require-plugin-pwa-debug",
    getPluginRule("require-plugin-pwa-debug"),
    {
        invalid: [
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                pwaHead: [],",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "requirePluginPwaDebug" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "const pwaOptions = {",
                    "    pwaHead: [],",
                    "};",
                    "",
                    "export default {",
                    "    plugins: [",
                    '        ["@docusaurus/plugin-pwa", pwaOptions],',
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "requirePluginPwaDebug" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                debug: false,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "requirePluginPwaDebugValue" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "const process = {",
                    "    env: {",
                    '        DOCUSAURUS_PWA_DEBUG: "true",',
                    "    },",
                    "};",
                    "",
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    '                debug: process.env.DOCUSAURUS_PWA_DEBUG === "true",',
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "requirePluginPwaDebugValue" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    '                debug: process.env["CUSTOM_PWA_DEBUG"] === "true",',
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "requirePluginPwaDebugValue" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                debug: true,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "requirePluginPwaDebugValue" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                options: [
                    {
                        allowBooleanLiteralTrue: false,
                    },
                ],
            },
        ],
        valid: [
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                debug: true,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    '                debug: process.env["DOCUSAURUS_PWA_DEBUG"] === "true",',
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "const isPwaDebugEnabled =",
                    '    process.env.DOCUSAURUS_PWA_DEBUG === "true";',
                    "",
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                debug: isPwaDebugEnabled,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "const pwaOptions = {",
                    '    debug: process.env["DOCUSAURUS_PWA_DEBUG"] === "true",',
                    "};",
                    "",
                    "export default {",
                    "    plugins: [",
                    '        ["@docusaurus/plugin-pwa", pwaOptions],',
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    '                debug: process.env["CUSTOM_PWA_DEBUG"] === "true",',
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
                options: [
                    {
                        allowedEnvVarNames: ["CUSTOM_PWA_DEBUG"],
                    },
                ],
            },
            {
                code: [
                    "const pwaOptions = getPwaOptions();",
                    "",
                    "export default {",
                    "    plugins: [",
                    '        ["@docusaurus/plugin-pwa", pwaOptions],',
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    plugins: [",
                    "        [",
                    '            "@docusaurus/plugin-pwa",',
                    "            {",
                    "                debug: false,",
                    "            },",
                    "        ],",
                    "    ],",
                    "};",
                ].join("\n"),
                filename: "src/config.ts",
            },
        ],
    }
);
