/**
 * @packageDocumentation
 * RuleTester coverage for `validate-navbar-item-position`.
 */
import { createRuleTester, getPluginRule } from "./_internal/ruleTester";

const ruleTester = createRuleTester();

ruleTester.run(
    "validate-navbar-item-position",
    getPluginRule("validate-navbar-item-position"),
    {
        invalid: [
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    '                { label: "Docs", to: "/docs", position: "Left" },',
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "validateNavbarItemPosition" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                output: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    '                { label: "Docs", to: "/docs", position: "left" },',
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
            },
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    type: "dropdown",',
                    '                    label: "Resources",',
                    "                    position: `RIGHT`,",
                    '                    items: [{ label: "API", to: "/api" }],',
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                errors: [{ messageId: "validateNavbarItemPosition" }],
                filename: "docs/docusaurus/docusaurus.config.ts",
                output: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    type: "dropdown",',
                    '                    label: "Resources",',
                    '                    position: "right",',
                    '                    items: [{ label: "API", to: "/api" }],',
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
            },
            {
                code: [
                    'const position = "center";',
                    "",
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    label: "Docs",',
                    '                    to: "/docs",',
                    "                    position,",
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                errors: [
                    {
                        messageId: "validateNavbarItemPosition",
                        suggestions: [
                            {
                                messageId: "setNavbarItemPositionLeft",
                                output: [
                                    'const position = "center";',
                                    "",
                                    "export default {",
                                    "    themeConfig: {",
                                    "        navbar: {",
                                    "            items: [",
                                    "                {",
                                    '                    label: "Docs",',
                                    '                    to: "/docs",',
                                    '                    position: "left",',
                                    "                },",
                                    "            ],",
                                    "        },",
                                    "    },",
                                    "};",
                                ].join("\n"),
                            },
                            {
                                messageId: "setNavbarItemPositionRight",
                                output: [
                                    'const position = "center";',
                                    "",
                                    "export default {",
                                    "    themeConfig: {",
                                    "        navbar: {",
                                    "            items: [",
                                    "                {",
                                    '                    label: "Docs",',
                                    '                    to: "/docs",',
                                    '                    position: "right",',
                                    "                },",
                                    "            ],",
                                    "        },",
                                    "    },",
                                    "};",
                                ].join("\n"),
                            },
                        ],
                    },
                ],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    label: "Docs",',
                    '                    to: "/docs",',
                    "                    position: 1,",
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                errors: [
                    {
                        messageId: "validateNavbarItemPosition",
                        suggestions: [
                            {
                                messageId: "setNavbarItemPositionLeft",
                                output: [
                                    "export default {",
                                    "    themeConfig: {",
                                    "        navbar: {",
                                    "            items: [",
                                    "                {",
                                    '                    label: "Docs",',
                                    '                    to: "/docs",',
                                    '                    position: "left",',
                                    "                },",
                                    "            ],",
                                    "        },",
                                    "    },",
                                    "};",
                                ].join("\n"),
                            },
                            {
                                messageId: "setNavbarItemPositionRight",
                                output: [
                                    "export default {",
                                    "    themeConfig: {",
                                    "        navbar: {",
                                    "            items: [",
                                    "                {",
                                    '                    label: "Docs",',
                                    '                    to: "/docs",',
                                    '                    position: "right",',
                                    "                },",
                                    "            ],",
                                    "        },",
                                    "    },",
                                    "};",
                                ].join("\n"),
                            },
                        ],
                    },
                ],
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
        ],
        valid: [
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    '                { label: "Docs", to: "/docs", position: "left" },',
                    '                { label: "Rules", to: "/rules", position: "right" },',
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "const position = getNavbarPosition();",
                    "",
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    "                {",
                    '                    label: "Docs",',
                    '                    to: "/docs",',
                    "                    position,",
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    '                { label: "Docs", to: "/docs" },',
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        footer: {",
                    "            links: [",
                    "                {",
                    '                    title: "Docs",',
                    "                    items: [",
                    '                        { label: "Docs", to: "/docs", position: "center" },',
                    "                    ],",
                    "                },",
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                filename: "docs/docusaurus/docusaurus.config.ts",
            },
            {
                code: [
                    "export default {",
                    "    themeConfig: {",
                    "        navbar: {",
                    "            items: [",
                    '                { label: "Docs", to: "/docs", position: "center" },',
                    "            ],",
                    "        },",
                    "    },",
                    "};",
                ].join("\n"),
                filename: "src/config.ts",
            },
        ],
    }
);
